model_list:
  - model_name: command-r-plus
    litellm_params:
      model: command-r-plus
  - model_name: command-r
    litellm_params:
      model: command-r

litellm_settings:
  drop_params: True

general_settings: 
  master_key: sk-7ZrAS5RZPHrUmGXh4bFb82A7E6214987B12eE3378b8dC399
